# Data

In [66]:
data = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies"""

In [67]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [68]:
tokenizer = Tokenizer()

In [69]:
import nltk
nltk.download('punkt')
sentences = nltk.sent_tokenize(data)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\rahul\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [70]:
sentences[2]

'The total duration of the course is 7 months.'

In [71]:
tokenizer.fit_on_texts(sentences)

In [72]:
assigned_num = tokenizer.word_index # tells which word is assigned with which number

In [73]:
data = tokenizer.texts_to_sequences(sentences)

In [74]:
data[2]

[1, 71, 72, 6, 1, 12, 7, 54, 73]

In [75]:
input_seq = []
for i in range(0,len(data)):
    for j in range(1,len(data[i])):
        input_seq.append(data[i][:j+1])

In [76]:
maxim = 0;
for i in range(0,len(input_seq)):
    maxim = max(maxim,len(input_seq[i]));
print(maxim)

60


In [77]:
from keras.utils import pad_sequences
input_seq = pad_sequences(input_seq,padding='pre',maxlen=maxim)

In [78]:
input_seq

array([[  0,   0,   0, ...,   0,  93,   1],
       [  0,   0,   0, ...,  93,   1,  13],
       [  0,   0,   0, ...,   1,  13,  11],
       ...,
       [  0,   0,   0, ..., 279,  18, 280],
       [  0,   0,   0, ...,  18, 280, 281],
       [  0,   0,   0, ..., 280, 281, 282]])

In [79]:
x = input_seq[:,:-1]
y = input_seq[:,-1]

In [80]:
x

array([[  0,   0,   0, ...,   0,   0,  93],
       [  0,   0,   0, ...,   0,  93,   1],
       [  0,   0,   0, ...,  93,   1,  13],
       ...,
       [  0,   0,   0, ..., 278, 279,  18],
       [  0,   0,   0, ..., 279,  18, 280],
       [  0,   0,   0, ...,  18, 280, 281]])

In [81]:
y

array([  1,  13,  11,   7,   1,  12,  42,  15,  43,  53,  68,  13, 147,
       148,   1,  12,  94,   5,  44,  29,  95,  30,   2,   8,   4,  26,
        44,  69,   6,  31,  70,  45,   7,   1,  71,  72,   6,   1,  12,
        71,  72,   6,   1,  12,   7,  54,  73,   1,  71,  12,  42, 149,
        70,  54,  31,  55, 150,   7,   1,  96,   6,   1,  68,  13,   9,
        19, 151,   1, 152, 153,  97, 154,  97, 155,  15,  43,  53,  43,
       156, 157,  15,  43,  53, 158,  15, 159,  74,  98, 160, 161,  98,
       162,  75,  99,   2,  10, 163,   1, 164,  96,  76,  77, 100,  33,
        14, 165,  33,  43,  53,  68,  13, 166,   9, 101,  74,  20, 102,
        19,   5,  78,   6,  21,  13, 102,  20, 101,  74, 167,  56,  46,
         5,  78,   6,  21, 168, 169,  22,   3, 104,   5, 105,  34,   3,
        47,   5, 106,   6,   1,  34,  16,  35,  17,  56, 170,  32, 107,
        22,   2, 104,   5,  34,   2,  10, 171, 172,  20,  57,   1, 106,
        10,   3, 173,   1, 108, 174,  21,  58, 176,   4,  79,  4

In [82]:
# our setup is multiclass classification

In [83]:
import numpy as np
element_counts = np.unique(y)
print(len(element_counts))
print(len(y))

272
875


In [84]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y, num_classes = len(assigned_num)+1)

In [85]:
x.shape

(875, 59)

In [86]:
y.shape

(875, 283)

In [89]:
from keras import Sequential
from keras.layers import Dense,LSTM,Embedding,Flatten

model = Sequential()
model.add(Embedding(input_dim=len(assigned_num), output_dim=100, input_length=59))
model.add(LSTM(150,return_sequences=True))
model.add(LSTM(150,return_sequences=True))
model.add(LSTM(150,return_sequences=False))
model.add(Dense(len(assigned_num)+1,activation='softmax'))
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 59, 100)           28200     
                                                                 
 lstm_6 (LSTM)               (None, 59, 150)           150600    
                                                                 
 lstm_7 (LSTM)               (None, 59, 150)           180600    
                                                                 
 lstm_8 (LSTM)               (None, 150)               180600    
                                                                 
 dense_2 (Dense)             (None, 283)               42733     
                                                                 
Total params: 582,733
Trainable params: 582,733
Non-trainable params: 0
_________________________________________________________________


In [90]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [132]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.callbacks import EarlyStopping
history = model.fit(x,y, epochs=100)

In [101]:
def predict_output(text):
    ans = text
    for i in range(5):
        tokenizer.fit_on_texts([text])
        token_text = tokenizer.texts_to_sequences([text])
        token_text = pad_sequences(token_text,padding='pre',maxlen=maxim-1)
        pos = np.argmax(model.predict(token_text))
        
        for word,index in tokenizer.word_index.items():
            if index==pos:
                ans = ans + ' ' + word
                text = word
    return ans

# Prediction

In [131]:
# Prediction 1
text = "SQL for "
print(predict_output(text))

1/1 [==============================] - 0s 28ms/step
SQL for  joining you sessions spreadsheets for
